name: publish-package

on:
  push:
    branches:
      - main

env:
  SOURCE_FOLDER: ./StringLibrary/
  NUGET_FOLDER: ./StringLibrary/bin/Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Deploy-Package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Build With DOTNET
        run: |
          cd $SOURCE_FOLDER
          dotnet pack --configuration Release
        shell: bash
      - name: Publish Nuget to GitHub Packages
        run: dotnet nuget push $NUGET_FOLDER/*.nupkg -s https://nuget.pkg.github.com/chris-catt -k $GITHUB_TOKEN
        shell: bash
